export { default as Developer } from '../assets/images/developer.jpg'
export { default as DeveloperCropped } from '../assets/images/developerCropped.jpg'
export { default as Typing } from '../assets/images/typing.gif'
export { default as BlueBoyTyping } from '../assets/images/typing_nothought.gif'
export { default as Coding } from '../assets/images/coding.gif'
export { default as EnhancedHii } from '../assets/images/shreyalanding.jpg'
export { default as Signature } from '../assets/images/signSVG1.svg' 

// projects
export { default as I1 } from '../assets/images/1.png'
export { default as I2 } from '../assets/images/parijana1.png'
export { default as I3 } from '../assets/images/parijana2.png'
export { default as I4 } from '../assets/images/parijana3.png'
export { default as I5 } from '../assets/images/parijana4.png'
export { default as I6 } from '../assets/images/parijana5.png'
export { default as I7 } from '../assets/images/parijana6.png'
// export { default as I8 } from '../assets/images/parijana7.png'
export{ default as g1 } from '../assets/images/g1.png'
export{ default as g2 } from '../assets/images/g2.png'
export{ default as g3 } from '../assets/images/g3.png'
export{ default as g4 } from '../assets/images/g4.png'
export{ default as g5 } from '../assets/images/g5.png'
export{ default as g6 } from '../assets/images/g6.png'
export{ default as g7 } from '../assets/images/g7.png'
export{ default as g8 } from '../assets/images/g8.png'
export{ default as g9 } from '../assets/images/g9.png'
export{ default as g10 } from '../assets/images/g10.png'
export{ default as g11 } from '../assets/images/g11.png'

export { default as kishori } from '../assets/images/kishori.png'
export { default as kishoriLogo } from '../assets/images/KishoriLogo.png'
export { default as kishoriImage } from '../assets/images/kishoriImage.png'
export { default as kishoriImage2 } from '../assets/images/kishoriImage2.png'
export { default as kishoriImage3 } from '../assets/images/kishoriImage3.png'

export { default as kishori1 } from '../assets/images/kishori1.png'
export { default as kishori2 } from '../assets/images/kishori2.png'
export { default as kishori3 } from '../assets/images/kishori3.png'
export { default as kishori4 } from '../assets/images/kishori1.jpg'

// team
export { default as shreyaSonkar } from '../assets/images/shreyaSonkar.png'
export { default as shivani } from '../assets/images/shivani.png'
export { default as vibhu } from '../assets/images/vibhu.png'
export { default as dheeraj } from '../assets/images/dheeraj.png'
export { default as yaman } from '../assets/images/yaman.jpeg'
